config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students do
    resources :addresses
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :student

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @address = Address.new(address_params)
    @address.student_id = params[:student_id]

    @address.save

    redirect_to students_path(@address.student)
  end

  private

  def address_params
    params.require(:address).permit(:description, :street_address, :city, :state, :zip_code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.id = params[:id]

    @student.save

    redirect_to students_path(@students)
  end

  def show
    @address = Address.new
    @address.student_id = @student.id
  end

  def edit
  end

  def update
    @student.update(student_params)

    redirect_to student_path(@student)
  end

  def destroy
    @student
    @student.destroy

    redirect_to students_path
  end

    private

    def student_params
      params.require(:student).permit(:name)
    end

    def set_student
      @student = Student.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<h3>Fill in an Address</h3>

<%= form_for [@student, @address] do |f| %>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :street_address %><br/>
    <%= f.text_area :street_address %>
  </p>
  <p>
    <%= f.label :city %><br/>
    <%= f.text_area :city %>
  </p>
  <p>
    <%= f.label :state %><br/>
    <%= f.text_area :state %>
  </p>
  <p>
    <%= f.label :zip_code %><br/>
    <%= f.text_area :zip_code %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit <%= @student.name %> </h1>

<%= render partial: 'form' %>

app/views/students/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    Students List <br>
    <% @students.each do |student| %>
      <p><%= link_to student.name, student_path(student) %></p>
      <div class="button">
      <%= link_to "Delete", student_path(student), method: :delete %>
      </div>
      <% end %> <br>
      <%= link_to "Create a new student", new_student_path %>
  </body>
</html>

app/views/students/new.html.erb
<h1>Create a New Student</h1>

<%= render partial: 'form' %>

app/views/students/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Students</title>
  </head>
  <body>
    <h3><%= @student.name %></h3>
  </body>
</html>